// <auto-generated />
using System;
using CloudCare.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudCare.API.Migrations
{
    [DbContext(typeof(CloudCareContext))]
    [Migration("20251122214143_SyncPendingChanges")]
    partial class SyncPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudCare.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food & Snacks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Educational Supplies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cleaning Supplies"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Furniture & Fixtures"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Repairs & Maintenance"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Professional Services"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Marketing & Advertising"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Staff Wages"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Training & Development"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Licenses & Permits"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BillingCycle")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("text");

                    b.Property<int?>("RecurrenceSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.HasIndex("VendorId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CloudCare.API.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Debit Card"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 4,
                            Name = "E-Transfer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cheque"
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DaycareAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DaycareName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTime>("UserCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CloudCare.API.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Walmart"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Costco"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Staples"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Home Depot"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Best Buy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Private Marketplace"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Local Vendor"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Government"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Real Canadian Superstore"
                        },
                        new
                        {
                            Id = 11,
                            Name = "FreshCo"
                        },
                        new
                        {
                            Id = 12,
                            Name = "No frills"
                        },
                        new
                        {
                            Id = 13,
                            Name = "DollarStore"
                        },
                        new
                        {
                            Id = 14,
                            Name = "GiantTiger"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Value Village"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.Expense", b =>
                {
                    b.HasOne("CloudCare.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudCare.API.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudCare.API.Models.User", null)
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudCare.API.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CloudCare.API.Models.User", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
