// <auto-generated />
using System;
using CloudCare.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudCare.API.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20250715063304_UsersTable")]
    partial class UsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudCare.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food & Snacks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Educational Supplies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cleaning Supplies"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Furniture & Fixtures"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Repairs & Maintenance"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Professional Services"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Marketing & Advertising"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Staff Wages"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Training & Development"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Licenses & Permits"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.HasIndex("VendorId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20.00m,
                            CategoryId = 1,
                            Date = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Snacks for kids",
                            IsRecurring = false,
                            PaymentMethodId = 1,
                            UserId = 1,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 35.00m,
                            CategoryId = 3,
                            Date = new DateTime(2024, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toys purchase",
                            IsRecurring = true,
                            PaymentMethodId = 2,
                            UserId = 1,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50.00m,
                            CategoryId = 2,
                            Date = new DateTime(2024, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Field Trip Supplies",
                            IsRecurring = false,
                            PaymentMethodId = 1,
                            UserId = 1,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 22.50m,
                            CategoryId = 6,
                            Date = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Office Supplies restock",
                            IsRecurring = false,
                            PaymentMethodId = 1,
                            UserId = 1,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 80.00m,
                            CategoryId = 2,
                            Date = new DateTime(2024, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Books for reading time",
                            IsRecurring = false,
                            PaymentMethodId = 2,
                            UserId = 1,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 120.00m,
                            CategoryId = 4,
                            Date = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly Cleaning Service",
                            IsRecurring = true,
                            PaymentMethodId = 3,
                            UserId = 1,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 7,
                            Amount = 150.00m,
                            CategoryId = 1,
                            Date = new DateTime(2024, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Birthday Party expenses",
                            IsRecurring = false,
                            PaymentMethodId = 1,
                            UserId = 1,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 60.00m,
                            CategoryId = 6,
                            Date = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Printer Ink replacement",
                            IsRecurring = false,
                            PaymentMethodId = 2,
                            UserId = 1,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 95.00m,
                            CategoryId = 14,
                            Date = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Online Workshop for Staff",
                            IsRecurring = false,
                            PaymentMethodId = 1,
                            UserId = 1,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 25.00m,
                            CategoryId = 1,
                            Date = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Weekly Snacks",
                            IsRecurring = true,
                            PaymentMethodId = 3,
                            UserId = 1,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 45.99m,
                            CategoryId = 12,
                            Date = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly Software Subscription",
                            IsRecurring = true,
                            PaymentMethodId = 2,
                            UserId = 1,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 15.00m,
                            CategoryId = 2,
                            Date = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Art Supplies",
                            IsRecurring = false,
                            PaymentMethodId = 1,
                            UserId = 2,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 45.00m,
                            CategoryId = 1,
                            Date = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lunch for Staff",
                            IsRecurring = false,
                            PaymentMethodId = 3,
                            UserId = 2,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 120.00m,
                            CategoryId = 4,
                            Date = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly Cleaning Service",
                            IsRecurring = true,
                            PaymentMethodId = 2,
                            UserId = 2,
                            VendorId = 3
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Debit Card"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 4,
                            Name = "E-Transfer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cheque"
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DaycareAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DaycareName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UserCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaycareAddress = "123 Main St, Cityville",
                            DaycareName = "Happy Kids Daycare",
                            Email = "provider1@daycare.com",
                            Name = "Alice Johnson",
                            Notes = "Open weekdays 7am-6pm",
                            PhoneNumber = "555-1234",
                            UserCreated = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            WebsiteUrl = "https://happykidsdaycare.com"
                        },
                        new
                        {
                            Id = 2,
                            DaycareAddress = "456 Oak Ave, Townsville",
                            DaycareName = "Little Stars Childcare",
                            Email = "provider2@daycare.com",
                            Name = "Bob Smith",
                            Notes = "Accepts infants and toddlers",
                            PhoneNumber = "555-5678",
                            UserCreated = new DateTime(2024, 6, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            WebsiteUrl = "https://littlestarschildcare.com"
                        },
                        new
                        {
                            Id = 3,
                            DaycareAddress = "789 Pine Rd, Villagetown",
                            DaycareName = "Bright Minds Preschool",
                            Email = "provider3@daycare.com",
                            Name = "Carol Lee",
                            Notes = "Focus on early learning",
                            PhoneNumber = "555-9012",
                            UserCreated = new DateTime(2024, 6, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            WebsiteUrl = "https://brightmindspreschool.com"
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Walmart"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Costco"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Staples"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Home Depot"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Best Buy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Private Marketplace"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Local Vendor"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Government"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("CloudCare.API.Models.Expense", b =>
                {
                    b.HasOne("CloudCare.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudCare.API.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudCare.API.Models.User", null)
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudCare.API.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CloudCare.API.Models.User", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
